### ISSUE TITLE
Encryption passkey errors

### ISSUE THREAD

**Issue by Avatarus-one** [Jessecar96/SteamDesktopAuthenticator#12]
Whenever you leave the field asking for you current passcode blank, you get either unhandled exception (Manage encryption button) or a crash (on startup).

**Comment by AleksaSavic3** [comment]
More bugs:

1. Click Manage Encryption.
2. Enter correct passkey.
3. On the next screen, click X in the right side.
4. (Bug No.1) A screen for confirming the password opens, even if you clicked X to close the previous one.
5. Click X once again.
6. (Bug No.2) After a few seconds, program informs you that the password is removed.

I just clicked X instead of Cancel. Surely a bug.
