### ISSUE TITLE
S.D.A ERROR

### ISSUE THREAD

**Issue by wojoto** [Jessecar96/SteamDesktopAuthenticator#165]
Sorry for my english, i so bad with this language.
I have error with SDA,
https://www.youtube.com/watch?v=BWEBS4oQnTA
I try to re-install vcredist_x86 and NET.FRAMEWORK but it no help.
Thanks.

**Comment by pipe01** [comment]
Can you please copy the error message to pastebin and put the link?

**Comment by wojoto** [comment]
Of course
http://pastebin.com/w0227832

**Comment by pipe01** [comment]
When you want to add a new account, you have to click on Setup New Account on the main form.

**Comment by wojoto** [comment]
I add this account 2 day ago...

**Comment by pipe01** [comment]
Have you linked it on your phone? If not, you may have deleted the maFiles, or they got removed by a bug. Either way, you can go [here](https://help.steampowered.com/#HelpWithLoginInfo?nav=authenticator), enter the details and the authenticator will be removed. When you add it again via SDA, make sure to backup both the generated maFile and the manifest, so that if this happens again you can paste them and recover it.

**Comment by wojoto** [comment]
Thanks <3
