### ISSUE TITLE
The Trade Confirmations are not WORKING, can someone help us please? Thanks so much!!

### ISSUE THREAD

**Issue by ernesto23** [Jessecar96/SteamDesktopAuthenticator#225]
## The Trade Confirmations are not WORKING, can someone help us please? Thanks so much!!

**i got this message always in the trade window from the " Steam Desktop Authenticator " Program:**

**"There was a problem loading details for that confirmation. Please try your request again later."**

Thanks for your Help ;)

**Comment by RATT78** [comment]
You're not alone friend. Same problem here, i was using an old version 1.0.6. After updating to the lastest version 1.0.7.2 the problem persist. I hope this issue will fix soon. Thx

**Comment by cooldudesunny** [comment]
Same is happening with me guys.. Please fix this...

**Comment by ernesto23** [comment]
well ¬¬ seen like we need the help of the experts here ;) =)

**Comment by RATT78** [comment]
Just in case that may help to figure where is the problem check your DEBUG.log file and copy/paste the last error show (or delete it and let it be created again when the error show the next time). Mine says:

[1119/024214:ERROR:renderer_main.cc(200)] Running without renderer sandbox

**Comment by rem2beast** [comment]
Like RATT78 said, doing the auto confirm seems to "fix" it/allow it to work

**Comment by RATT78** [comment]
The option "Periodically Check For New Confirmations and Show a Popup when they arrive", also help, with this a popup show asking to confirm trade/market (we need to click twice), for this popup show you need to select the account that generate the confirmation event (in case you have mora than one account). This way we still need to manually confirm, instead of use the auto confirmations.

**Comment by ernesto23** [comment]
Thanks so much to everyone, works the option: File -> Settings -> "Periodically Check For New Confirmations and Show a Popup when they arrive" (and click twice to confirm or cancel)...

Thanks a lot to Everyone buddies: RATT78,  rem2beast and everyone here!! 
Regards and have a lot of nices days   (^^)

**Comment by RATT78** [comment]
I read in other forums that some user have the same issue with the iOS/android app in their smartphones. Maybe the problem came from Steam/Valve itself and not from SDA.

**Comment by PrinceOfAngels** [comment]
How to import from my android device ??? It keeps saying ADB not found ..... I already made everything it asked there connected the phone in my pc and still the same anyone know how to do it ?

**Comment by RATT78** [comment]
Just an update, it now working fine, SDA and the mogile app are now working normally, probably was an issue originated from Steam an not from SDA. Now we can use our SDA normally.

**Comment by Jessecar96** [comment]
Re-login to your account using the option in the "Selected Account" menu. This fixes it 99% of the time.

**Comment by Syncshot** [comment]
I know this is an old thread but this problem is still happening to me. I have tried all of the above things to fix it but when I try to "Login again" under "Selected Account" it does not work and I get an error message saying:

"Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit. the application will close immediately.

An attempt was made to access a socket in a way forbidden by its access permissions 104.96.189.16:443."

Details:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions 104.96.189.16:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2116.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Steam Desktop Authenticator
    Assembly Version: 1.0.8.1
    Win32 Version: 1.0.8.1
    CodeBase: file:///C:/Users/Admin/Desktop/SteamDAuth.1.0.8.1/Steam%20Desktop%20Authenticator.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2116.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
CommandLine
    Assembly Version: 1.9.71.2
    Win32 Version: 1.9.71.2
    CodeBase: file:///C:/Users/Admin/Desktop/SteamDAuth.1.0.8.1/CommandLine.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2116.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2116.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2116.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.2.20802
    CodeBase: file:///C:/Users/Admin/Desktop/SteamDAuth.1.0.8.1/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2116.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2116.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2116.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SteamAuth
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Admin/Desktop/SteamDAuth.1.0.8.1/SteamAuth.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by pipe0482** [comment]
Thats looks like a firewall issue to me, try disabling it.

**Comment by LordGorzul** [comment]
Having that issue right now, using version 1.0.8.1
Unable to open confirmations, i tried the advice above, setting to auto accept and doing the popup, check every 5s and so on, tried every option including forcing and re-login. Nothing is helping. 
I do not have a firewall or AV.
