### ISSUE TITLE
SDA on multiple computers

### ISSUE THREAD

**Issue by SlipperyNipple** [Jessecar96/SteamDesktopAuthenticator#36]
If set up on another computer it says, SDA has already been activated. Is there a way to have SDA on multiple computers?

**Comment by hyt47** [comment]
Create a copy of the first program and place it on your secondary PC. 
But if the app is already running on the first PC this might not good for u.
 I don't know what happens when u activate 2 Mobile Authenticators. 

Steam allows only one Mobile Authenticator to authorize stuff. 

The best solution is to create a backup and store it somewhere safe, and to place the app on a USB stick.

**Comment by Jessecar96** [comment]
All you need to do is copy the folder "maFiles" to where you have SDA on your other computer.
