### ISSUE TITLE
Help program does not open

### ISSUE THREAD

**Issue by Silentblood97** [Jessecar96/SteamDesktopAuthenticator#396]
I have been using SDA almost if not since it started , but since a week ago I have been having a problem with it , I try to open the exec file , nothing happens , I check to see if its open on processes but nothing , already tried updating it also nothing , the best I could do was deleate mafiles folder ( I backed it up obviously ) and tried opening and it did , so the problem is somewhere on mafiles folder , can anyone help me please? Thanks

Edit : If I am not mistaken the problem is on manifest.json

**Comment by matiasvll** [comment]
I have the same problem pal, have you found any solutions?

**Comment by Silentblood97** [comment]
Nope , had to remake a new SDA , had to wait 15days for market and trades

**Comment by pipe0482** [comment]
You could have copied the maFiles over.

El 11/08/2017 17:11, "Silentblood97" <notifications@github.com> escribió:

Nope , had to remake a new SDA , had to wait 15days for market and trades

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/396#issuecomment-321839904>,
or mute the thread

**Comment by Silentblood97** [comment]
I literaly did everything I could think of , including that .
