### ISSUE TITLE
No Transfer Option

### ISSUE THREAD

**Issue by Barnzy** [Jessecar96/SteamDesktopAuthenticator#477]
G'day all, 

I am really interested in using the SDA, however, I cannot transfer from Mobile to Desktop.. Is there a way? I do not want to have to wait 15 Days instead of 2 Days.

Thanks

**Comment by sebastianbassen** [comment]
Is your phone rooted?

**Comment by Barnzy** [comment]
No, it is not. I have an IOS device and I saw the guide but I cannot seem to get all those secrets and stuff.

**Comment by linkjayy** [comment]
Unless you are rooted, or have your secret keys somehow, you cannot use SDA.

You need to unlink your current mobile key, root or jailbreak, generate the stuff with SDA, then enter it in on your phone. Then you have it in both places.

**Comment by Barnzy** [comment]
I saw a tutorial and some guy got the code. He was on Mac not Windows. I tried the same method, but I do not understand how he got there.

**Comment by linkjayy** [comment]
What I said still stands. Unless you somehow obtained the security key before your phone stored it, it is near impossible to get it.

Androids and iPhones are designed so that appdata is stored away from the user to access and other apps. This way, you and any apps cannot mess with any app's data. Only the app can.

The Steam secret key is stored in its own data folder in an unaccessable part of the system. It can only be obtained through root or jailbreak. That is why it's called rooting, because you're allowing certain apps to have root access such as a file viewer.

**Comment by pohuiusemail4741** [comment]
maybe can help
here: https://github.com/JustArchi/ArchiSteamFarm/wiki/Escrow
