### ISSUE TITLE
SDA won't import from rooted Android

### ISSUE THREAD

**Issue by Shimabun** [Jessecar96/SteamDesktopAuthenticator#512]
I've done all the steps to verify the program has worked. I installed all of the ADB files and made sure they were properly placed in the SDA folder. 

My phone is rooted and has Superuser on it, and debugging is enabled. Whenever I open SDA.exe, it will download Visual C++ every time, and when I click on "Import from Android Device", it will be frozen at the root method / extraction process. 

I waited for a full 30 minutes with no results, and I'm wondering how could I possibly remedy this?

**Comment by eshao731** [comment]
I have the same problem. How to solve it?

**Comment by eshao731** [comment]
![image](https://user-images.githubusercontent.com/31184871/41393203-3f3b7f66-6fd7-11e8-951c-a142ed1bc199.png)

**Comment by OneCrazyRussian** [comment]
Same error for me, my phone uses Magisk as a root solution.

**Comment by Pingger** [comment]
My SDA just deadlocks at that point doesn't do shit, and it no longer responds to any button presses! I have the steamguard file! WHY CAN'T WE JUST ENTER THE STEAM GUARD FILE?! The ADB is buggy as hell. (well not the adb, but the way you 'developed' your access to it, since entering the command manually works fine ...)

**Comment by LillieSatou** [comment]
Confirming this too.
Android 4.4.2 (rooted)

Installing ADB as instructed & entering the path manually will work. **YOU MUST HAVE A ROOTED DEVICE TO DO THIS.**

**Comment by cody1997** [comment]
always freeze on "Checking root.."  :C
