### ISSUE TITLE
"Failed To Load Confirmations"

### ISSUE THREAD

**Issue by JustCallMeAlec** [Jessecar96/SteamDesktopAuthenticator#530]
I suddenly get this error whenever I try to load confirmations across all accounts. It recommends I try "Force session refresh" which causes another error to recommend using "login again" which causes a "General Error" to occur. Also Family View is off.
![failedtoloadconfirmations](https://user-images.githubusercontent.com/28990089/43879021-f4ceb3f2-9b6f-11e8-92a7-c1d692bd37c5.png)
![forcesessionrefresh](https://user-images.githubusercontent.com/28990089/43879022-f4dc0fb6-9b6f-11e8-8b81-c6748be2eab8.png)
![loginagain](https://user-images.githubusercontent.com/28990089/43879023-f4eb403a-9b6f-11e8-8abe-2603f98d51ad.png)

**Comment by Mr-Oneal** [comment]
You’re not the only one, it appears I have the same issue. My trade confirmations won’t load. A massage appears, saying that I have to force a refresh, in the end it just gives a general failure error. 
![steam](https://user-images.githubusercontent.com/42253697/43927759-6451ac2a-9be3-11e8-8994-75e50d21e4eb.png)

**Comment by JustCallMeAlec** [comment]
Well at least I'm not alone in this...

**Comment by Mr-Oneal** [comment]
Hey Alec, mine is working again, I know what I was doing wrong... After checking again and doing the process of login, I realize that I was writing the password for the authenticator instead of the password for my Steam account for the login (I Feel Dumb for that). So yes, maybe that’s your error too, write the password of your steam account. I hope that fixes yours.
