### ISSUE TITLE
Unable to import Steam Accounts from Android

### ISSUE THREAD

**Issue by Saturn-Enceladus** [Jessecar96/SteamDesktopAuthenticator#562]
I've compiled the latest update to the master branch which includes the Android fix from May 2018 that has been pushed since the last release in Mar 2018, and I still cannot get the app to import from the Steam app. It just says "Checking for Steam app" indefinitely. I have a Motorola Z3 running Android 8.1.0 if that makes any difference.

**Comment by Saturn-Enceladus** [comment]
[https://feen.us/ru41dd.png](url)

**Comment by jungletek** [comment]
Same here, shit's broken.

**Comment by 21cret** [comment]
we're also stuck in this

**Comment by Ichigo0Soul** [comment]
Same exact problem here. Galaxy S8+ on Android 8.0.0

**Comment by YuanYu-Double** [comment]
mabay your phone need 'root'

**Comment by jungletek** [comment]
> mabay your phone need 'root'

If you're already rooted, you don't really need this; you can just use Titanium Backup to backup Steam's data and restore it after you wipe your phone. You don't even need to log back in to Steam, and you certainly avoid all the nonsense of market restrictions because you switched your authenticator.
