### ISSUE TITLE
XP Support

### ISSUE THREAD

**Issue by PrzemoVi** [Jessecar96/SteamDesktopAuthenticator#594]
Hi.
So SDA does not support xp, but you know, still many peoples are playing on steam on windows xp. In example on hardware that is not compatybile with win7 or linux. (..my D531.. ;/).
So could you add xp to build targets or create special version for xp?

**Comment by routemasters** [comment]
How do you run Steam on XP in 2019? But you can check this mod;

https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47

**Comment by PrzemoVi** [comment]
So
Here you can find last-working steam package with disabled updates:
https://ia800708.us.archive.org/22/items/steam_201901/steam_201901_archive.torrent
You have to install steam from standard installer first and then replace all files in installdir with these from package.

**Comment by free020603** [comment]
Windows XP and Windows Vista Support
Starting on January 1 2019, Steam will officially stop supporting the Windows XP and Windows Vista operating systems. This means that after that date the Steam Client will no longer run on those versions of Windows. In order to continue running Steam and any games or other products purchased through Steam, users will need to update to a more recent version of Windows.

The newest features in Steam rely on an embedded version of Google Chrome, which no longer functions on older versions of Windows. In addition, future versions of Steam will require Windows feature and security updates only present in Windows 7 and above.

For the remainder of 2018 Steam will continue to run and to launch games on Windows XP and Windows Vista, but other functionality in Steam will be somewhat limited. For example, new features such as the new Steam Chat will not be available. We encourage all users on these operating systems to upgrade to newer versions of Windows in order to have ongoing access to the latest features of Steam, and to ensure future access to all games and other Steam content.

**Comment by Jessecar96** [comment]
We cannot support windows xp due to our various libraries not supporting it either.
