### ISSUE TITLE
Error adding your phone number Steam returned GeneralFailure

### ISSUE THREAD

**Issue by BrukiFl** [Jessecar96/SteamDesktopAuthenticator#841]
Everything was working fine before the 1.0.11 update 😟

**Comment by Moonb1ade** [comment]
> Everything was working fine before the 1.0.11 update 😟

Hello. Yes, it used to work, but that's the fault of steam itself, and the sda developer is trying to fix everything, I'm sure of it. The question is how long do we wait.

**Comment by LostMVP1** [comment]
its a first update after three years, so let him cook :D

**Comment by 343intact** [comment]
Yeah, came here with the same issue. I have 3 accounts linked to sda. My main works just fine, no complications. Other 2 return error, saying that I have to login again. When I try to login, I get "generalfailure" every time. I can't delete my connections, I get an error. I can't just set up sda anew, because accounts are already linked to an authenticator (sda with errors). So 2/3 of my accounts are stuck in a strange limbo, where I have no control over them, even though the codes sda shows for them are always right, I just can't use confirm any trades, sales, etc.
