### ISSUE TITLE
SDA is not working anymore 

### ISSUE THREAD

**Issue by DeL1der** [Jessecar96/SteamDesktopAuthenticator#875]
Are there any alternatives to fix this? Shows it all the time
![Безымянный67 (2)](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/137718597/73a80fbb-2c78-4fcf-b566-ef9883d16e56)

**Comment by DeL1der** [comment]
When you log in, after refresh session the login pops up all the time

**Comment by dyc3** [comment]
This is a known issue, and SDA isn't going to get updated for a while. Jessecar96 themselves has said on discord that he's too busy to update SDA right now.

If you are interested, I maintain steamguard-cli. It's capable of reading the exactly the same maFiles that SDA does, so you don't have to deal with a trade ban. You can download it here: https://github.com/dyc3/steamguard-cli/releases

Read the quickstart here: https://github.com/dyc3/steamguard-cli/blob/master/docs/quickstart.md

Alternatively, some people have made community patches (#859), and there's other software that does the same thing, if you feel comfortable with that kind of thing. Otherwise, you can transfer the authenticator to the official steam mobile app, but that does cause a 2 day trade ban.

**Comment by icitak1** [comment]
@dyc3 what is jessecar's discord?

**Comment by dyc3** [comment]
I have no idea.

**Comment by icitak1** [comment]
@dyc3 so how do you know that jesse said "he's too busy to update SDA right now"

**Comment by dyc3** [comment]
It's second hand information, I heard it from somebody else on one of these threads.

**Comment by MarcusRichardson** [comment]
move to archi 2fa

**Comment by sf3k** [comment]
> If you are interested, I maintain steamguard-cli. It's capable of reading the exactly the same maFiles that SDA does, so you don't have to deal with a trade ban. You can download it here: https://github.com/dyc3/steamguard-cli/releases
> 
> Read the quickstart here: https://github.com/dyc3/steamguard-cli/blob/master/docs/quickstart.md

I switched to this project and I can confirm it works well.
It only needs a better tutorial or a youtube video for a layman.

**Comment by fegeg** [comment]
> > If you are interested, I maintain steamguard-cli. It's capable of reading the exactly the same maFiles that SDA does, so you don't have to deal with a trade ban. You can download it here: https://github.com/dyc3/steamguard-cli/releases
> > Read the quickstart here: https://github.com/dyc3/steamguard-cli/blob/master/docs/quickstart.md
> 
> I switched to this project and I can confirm it works well. It only needs a better tutorial or a youtube video for a layman.

Could you please help me with a short guide on how to? I have a SDA maFile but I dont exactly know how to add it to steamguard-cli.

**Comment by Bluesette** [comment]
> > > If you are interested, I maintain steamguard-cli. It's capable of reading the exactly the same maFiles that SDA does, so you don't have to deal with a trade ban. You can download it here: https://github.com/dyc3/steamguard-cli/releases
> > > Read the quickstart here: https://github.com/dyc3/steamguard-cli/blob/master/docs/quickstart.md
> > 
> > 
> > I switched to this project and I can confirm it works well. It only needs a better tutorial or a youtube video for a layman.
> 
> Could you please help me with a short guide on how to? I have a SDA maFile but I dont exactly know how to add it to steamguard-cli.

x2

**Comment by sf3k** [comment]
1. Download https://github.com/dyc3/steamguard-cli/releases/download/v0.9.4/steamguard.exe to C:\Temp
2. Open Comman Prompt and execute one of these two commands:
C:\Temp\steamguard.exe -m C:\Temp\SDA-1.0.11.broken\maFiles -u sf3k code
C:\Temp\steamguard.exe -m C:\Temp\SDA-1.0.11.broken\maFiles -u sf3k trade

where "C:\Temp\SDA-1.0.11.broken\maFiles" is a folder with SDA maFiles, sf3k is my acc name
