### ISSUE TITLE
I need MaFile

### ISSUE THREAD

**Issue by n457t** [Jessecar96/SteamDesktopAuthenticator#878]
Hello.
Is there any easy way to get MaFile in another way since SDA doesn't work now? Method must be simple enough for dumb people like me, who don't know anything about programming, to do it...

**Comment by dyc3** [comment]
If you are interested, I maintain steamguard-cli. It's capable of reading the exactly the same maFiles that SDA does, so you don't have to deal with a trade ban. You can download it here: https://github.com/dyc3/steamguard-cli/releases

Read the quickstart here: https://github.com/dyc3/steamguard-cli/blob/master/docs/quickstart.md

Alternatively, some people have made community patches (#859), and there's other software that does the same thing, if you feel comfortable with that kind of thing. Otherwise, you can transfer the authenticator to the official steam mobile app, but that does cause a 2 day trade ban.

**Comment by bokaswt** [comment]
That files should be in a sub directory "maFiles" of the directory you installed SDA. But you cannot do anything with those unless you have another programm that can work with them.

**Comment by n457t** [comment]
I think i do it correctly with @dyc3 help. Now i need 15 days. Thank you :)
