### ISSUE TITLE
Still confirmation not working

### ISSUE THREAD

**Issue by neb1r** [Jessecar96/SteamDesktopAuthenticator#880]
i upgraded to .11 version. And still confirmation not working. I did login again thing and still not working.

**Comment by dyc3** [comment]
This is a known issue, and SDA isn't going to get updated for a while. Jessecar96 themselves has said on discord that he's too busy to update SDA right now.

If you are interested, I maintain steamguard-cli. It's capable of reading the exactly the same maFiles that SDA does, so you don't have to deal with a trade ban. You can download it here: https://github.com/dyc3/steamguard-cli/releases

Read the quickstart here: https://github.com/dyc3/steamguard-cli/blob/master/docs/quickstart.md

Alternatively, some people have made community patches (#859), and there's other software that does the same thing, if you feel comfortable with that kind of thing. Otherwise, you can transfer the authenticator to the official steam mobile app, but that does cause a 2 day trade ban.

**Comment by FusionJura** [comment]
I saw GIT project that went our, It allegedly fix the issue, https://github.com/therepower/SteamDesktopAuthenticator-Temporary-Fix

In my opinion transferring to this is *risky*, I didn't look all code, but its totally different programming language.
They KEY chang to STEAM api was confermation endpoint:
- API "mobileconf/conf" was changed to "mobileconf/getlist"
- Response from that API was changed from HTML to JSON


Summary:
- For those who use SteamDesktopAuthentificator, they need to be carful when transfering to new GIT project (safty reason)
- For those who use custom script (python, node, etc) can easily fix their authentificator
