### ISSUE TITLE
Unable to confirm non-US phone number

### ISSUE THREAD

**Issue by MediArgentum** [Jessecar96/SteamDesktopAuthenticator#9]
I type in my phone number in the given format (+995 5********) and then nothing happens. I'm back at the main window and I'm not receiving any sms. My phone IS capable of receiving sms. Does this have something to do with the fact that my number starts with +995 and it is unsupported or something?
Also, I do have my country and my phone number specified through the official Steam website. That doesn't seem to help though.

**Comment by Jessecar96** [comment]
I don't see how this can happen without you hitting cancel. I'm unable to replicate this.

**Comment by geel9** [comment]
This can happen if Steam fails to add your phone number. You need to go to the Steam website and add the phone number there. If it's still asking for your phone number, it sounds like a Steam problem.

**Comment by MediArgentum** [comment]
I have verified my phone number on the official Steam website. I did receive an SMS code when I clicked "Verify" from there and all is correct with that. After that, I have tried running this app again and the exact same scenario happens as I've described in this issue.
So, I tried removing my phone number from Steam, then waiting half an hour and then re-adding my phone number there. Everything worked well. Waited 20 more minutes after that. Then I tried to use this app again. Unfortunately, the exact same scenario keeps repeating. I really have no idea what's causing this problem.

**Comment by Jessecar96** [comment]
If it's not working on Steam's website either this is not an issue with SDA.

**Comment by MediArgentum** [comment]
So, I've downloaded Andy - The android emulator for PC and turned on Steam Mobile Authenticator from there. Everything works fine there. Since this is an emulator it's slow but I expected it to be even slower than it is.

Steam Desktop Authenticator still doesn't work for me. I tried compiling it for myself using Visual Studio 2015 Community. I downloaded both projects, Steam Desktop Authenticator and SteamAuth, and yet I'm getting a lot of errors when I try to compile it for myself. I guess that has something to do with Jasonsoft and metroframework or something, I don't even know what those are.

**Comment by resrep** [comment]
I have the same problem and I have info you might find helpful.

I downloaded SDA 0.2.3 on wednesday and successfully put a mobile authenticator on my account. Today I downloaded SDA 0.3 and without thinking I deleted the previous version, without backing up the maFiles and such. I said screw it I'll make a new one, I hadn't reached the 7 days required for the trade hold to be disabled anyway, so I removed the authenticator from my account and tried to make a new one, only now I have this exact problem, everything works fine until it gets to the part where I have to write my phone number, I write +30 69...... and after a second the window closes without anything happening, and if I redo the process, the same thing happens.

On wednesday I actually HAD NOT added a phone number to my steam account at all, and it worked fine, yesterday I added my phone number to my steam account so I could complete the community badge and level up and now it is not working, so I thought maybe that's at fault, so I removed my phone number from my account and tried, same thing as always, I re-added the phone number to my steam account and same thing again, I even received the sms from steam to verify my number fine in both the removal and the re-addition. And yes, I have tried to redownload SDA 0.2.3 and do the process there again, same thing as with the new version so I think this might be a steam issue and not something on your end but I have no idea what do and it is driving me crazy, I'm kinda hoping it will be fixed on its own tomorrow since it seems to have gotten screwed up on its own anyway but the only thing I know is that I hate Valve right now.

**Comment by vlogerM** [comment]
The same problem here.
I have a short phone number: +48 XXX XXX XXX.
SDA version: 0.3.0
I tried many times, with number added to my account, and without adding it. SDA always want my number. When I type it the window disappear and I'm not receiving any sms.

**Comment by tehdogemaster** [comment]
um so how do I fix this problem? I'm sorta new to this stuff?

**Comment by Skaabais** [comment]
Same problem.

**Comment by tehdogemaster** [comment]
he keeps on ignoring us i think

**Comment by vlogerM** [comment]
No he isn't. Look over you previous comment. What you see?
"@Jessecar96 	Updated SteamAuth, fixes #53 #50 #9".
He made the fix for this issue (#9). We only need to wait for new version of Steam Desktop Authenticator I think.

**Comment by tehdogemaster** [comment]
ye it will take another 2 weeks

**Comment by resrep** [comment]
what's an easy way to compile the new version then? or do we have to wait for the next release?

**Comment by MediArgentum** [comment]
I don't know. But I'm hoping the next release will fix this issue! (Cause, I really don't wanna be using an emulator (even though that emulator is pretty good actually)). And if it's fixed, I'm gonna put this app in my Dropbox folder to have it both on my desktop and my laptop. I don't assume that's gonna be a problem, right?

**Comment by vlogerM** [comment]
I download the new version 0.3.1, and now everything is ok. Thank you for the fix.

**Comment by MediArgentum** [comment]
After trying out this new release:

Error adding phone number. Steam returned "GeneralFailure".

Now it's giving me this message. Strange how it works on Steam and doesn't work on SDA.
I tried writing my number as "+995 5********" and "+9955********" (without space). Both give the same result mentioned above.

**Comment by resrep** [comment]
I'm not sure how this happened, I tried out 0.3.1 asap and it worked

**Comment by Jessecar96** [comment]
This is a problem with SteamAuth if you're still having issues, I will direct you there: https://github.com/geel9/SteamAuth
