### ISSUE TITLE
Add new account error!

### ISSUE THREAD

**Issue by KUGLEX** [Jessecar96/SteamDesktopAuthenticator#913]
I checked to see if it would work on any of the accounts I have I have 19 of them on none of them worked.

**Comment by DumbJoe** [comment]
Wow 19 accounts....lol what do you use those for? Grinding out them trading cards?

**Comment by merelenten** [comment]
I confirm that the creation of ma fille only works on Version 1.0.12.
But if I do not receive an sms to my number during the linking process and try to change it, then I will have to wait at least five minutes to do it.
sda only after 5 minutes offers offers to enter a new phone number and before that continues to send sms to the old number. Definitely this problem is on a third-party service that is implemented in new versions of sda. Because of this, it is a very big problem to use the mechanism of the new sda in programs for automatic binding of mafile

**Comment by ccsimplyspolit** [comment]
> I checked to see if it would work on any of the accounts I have I have 19 of them on none of them worked.

Download old version https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/download/1.0.12/SDA.1.0.12.zip
import/create new accounts
download latest version, click import account via .maFile

**Comment by Jessecar96** [comment]
Pre-release version 1.0.14 is now out that fixes this issue: https://github.com/Jessecar96/SteamDesktopAuthenticator/releases

**Comment by DumbJoe** [comment]
> Confirmations do not load on Windows 7 due to SSL/TLS issues.

Is there a way to fix those SSL/TLS issues so that confirmations work on windows 7?
